name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.10'
    
    - name: Cache pip packages
      uses: actions/cache@v4  # Updated to v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run all tests
      run: |
        pytest test_model.py -v
    
    - name: Run specific test groups
      run: |
        echo "Running parameter count test..."
        pytest test_model.py::test_parameter_count -v
        
        echo "Running accuracy test..."
        pytest test_model.py::test_first_epoch_accuracy -v
        
        echo "Running gradient tests..."
        pytest test_model.py::test_gradient_flow -v
        pytest test_model.py::test_gradient_magnitudes -v
        
        echo "Running robustness tests..."
        pytest test_model.py::test_noisy_inputs -v
        pytest test_model.py::test_edge_cases -v
        
        echo "Running batch size tests..."
        pytest test_model.py::test_batch_sizes -v

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: test-results
        path: |
          .pytest_cache
          __pycache__